export const ADD_FACTORY = "ADD_FACTORY";
export const UPDATE_FACTORY = 'UPDATE_FACTORY';
export const EDIT_FACTORY = 'EDIT_FACTORY';
export const SYNCH_CURRENT_FACTORY = 'SYNCH_CURRENT_FACTORY';
export const RESET_CURRENT_FACTORY = 'RESET_CURRENT_FACTORY';
export const PROCESS_ERRORS = 'PROCESS_ERRORS';
export const SOCKET_MESSAGE_IN= 'SOCKET_MESSAGE_IN';
export const SOCKET_MESSAGE_OUT = 'SOCKET_MESSAGE_OUT';

